language: java
jdk:
 - openjdk8
 
install: 
 - cd Serveur
 - mvn install -DskipTests
 
 - cd ../Moteur
 - mvn install -DskipTests
 
test:
 - cd ../Serveur
 - mvn test
 - cd ../Moteur
 - mvn test
 
services:
 - docker
 
before_script:
 - cd ../Serveur
 - docker build -t serveur .
 - cd ..
 - docker run -d --rm --name serveur -p 2480:8080 serveur
 
script:
 - sleep 10
 - cd Moteur
 - mvn exec:java
 