language: java
jdk:
 - openjdk11
<<<<<<< HEAD
 
install: 
 - mvn install -DskipTests

before_script:
=======
install: true
docker:
>>>>>>> 7f3ea4bcd937c2850f91d0acc6685b48fab9d5ad
 - docker build -t puerto-rico .
 
<<<<<<< HEAD
#script:
# - mvn install
# - mvn exec:javag
=======
script:
 - mvn test
 - docker run puerto-rico
>>>>>>> docker
