language: java
jdk:
 - openjdk8
 
install: 
 - cd Serveur
 - mvn install
 
 - cd ../Moteur
 - mvn install -DskipTests

test:
 - mvn test
 cd ..
 
services:
 - docker
 
before_script:
 - docker build -t serveur Serveur/.
 - docker run -d serveur -p 2480:8080 serveur
 
script:
 - cd Moteur
 - mvn exec:java
 - docker stop serveur
 