language: java
jdk:
 - openjdk8
 
install: 
 - cd Serveur
 - mvn install
 
 - cd ../Moteur
 - mvn install -DskipTests

test:
 - mvn test
 
before_script:
 - cd ../Serveur
 - docker build -t serveur .
 
script:
 - docker run --rm --name serveur -p 2480:8080 serveur
 