language: java
jdk:
 - openjdk11
 
 services:
  - docker
 
install: 
 - mvn install -DskipTests
 
docker:
 - docker build -t puerto-rico .
 
script:
 - mvn test
 - docker run puerto-rico
