language: java
jdk:
 - openjdk11
 
install: 
 - mvn install -DskipTests

before_script:
 - docker build -t puerto-rico .
 
<<<<<<< HEAD
#script:
# - mvn install
# - mvn exec:javag
=======
script:
 - mvn test
 - docker run puerto-rico
>>>>>>> docker
